id = "call-trans-opt-received"
name = "Call trans opt: received. 2-19-98 13:24:18 REC:Log> Theme"
authors = ["David C Cavalcante <davcavalcante@proton.me>", "Takk™ Innovate Studio <say@takk.ag>"]
<<<<<<< HEAD
version = "0.1.2"
=======
version = "0.1.1"
>>>>>>> e7a5670351a2dab30eee81fac5a84935c68028df
schema_version = 1
description = "📺 An iconic aesthetic of the shell screen from the 1999 film The Matrix, inspired by the film's opening command 'Call trans opt: received. 2-19-98 13:24:18 REC>'"
repository = "https://github.com/takk8is/call-trans-opt-received-2-19-98-13-24-18-rec-log-theme-for-zed"
