authors = ["David C Cavalcante <davcavalcante@proton.me>","Takk™ Innovate Studio <say@takk.ag>"]
description = "A iconic aesthetic of the shell screen from the 1999 film The Matrix, Inspired by the film's opening command 'Call trans opt: received. 2-19-98 13:24:18 REC>'"
id = "call-trans-opt-received"
name = "'Call trans opt: received. 2-19-98 13:24:18 REC:Log>'"
repository = "https://github.com/takk8is/call-trans-opt-received-2-19-98-13-24-18-rec-log-theme-for-zed"
schema_version = 1
version = "0.1.0"
